services:
  - type: web
    name: saleor-dashboard
    env: static
    buildCommand: npm ci --legacy-peer-deps && npm run build
    staticPublishPath: ./build/dashboard
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: API_URL
        sync: false
      - key: APP_MOUNT_URI
        value: /
      - key: STATIC_URL
        value: /
      - key: SKIP_SOURCEMAPS
        value: true
      - key: LOCALE_CODE
        value: EN
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
