name: Changesets

on:
  pull_request:
    types:
      - opened
      - labeled
      - edited
      - synchronize

jobs:
  changeset_present:
    # Adding 'skip changesets' label to the PR will skip this job
    if: ${{ !contains( github.event.pull_request.labels.*.name, 'skip changeset') && !startsWith(github.head_ref, 'changeset-release/') }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repo (full)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Changeset file lookup (git diff)
        run: |
          # Fetch target branch to compare against
          git fetch origin "${{ github.base_ref }}" --depth=1 || true

          # List files changed between base and head
          files=$(git diff --name-only "origin/${{ github.base_ref }}...HEAD")

          echo "Changed files:\n$files"

          if echo "$files" | grep -q '^\.changeset/'; then
            echo "Changesets found!"
          else
            echo "There is no changeset file in your pull request."
            exit 1
          fi
