name: "Periodic npm audit"

on:
  schedule:
    - cron: "0 3 * * 1" # weekly on Monday at 03:00 UTC
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  audit:
    name: npm audit
    permissions:
      contents: read
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install
        run: npm ci

      - name: Run npm audit
        run: npm audit --json > audit.json || true

      - name: Upload audit report
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: audit.json

      - name: Create issue when vulnerabilities found
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('audit.json', 'utf8'));
            const vuln = report.metadata && report.metadata.vulnerabilities ? report.metadata.vulnerabilities : null;
            const total = vuln ? vuln.total : 0;
            if (total > 0) {
              const body = `Automated npm audit detected ${total} vulnerabilities:\n\n` +
                `- critical: ${vuln.critical || 0}\n` +
                `- high: ${vuln.high || 0}\n` +
                `- moderate: ${vuln.moderate || 0}\n` +
                `- low: ${vuln.low || 0}\n\n` +
                `An artifact named \"npm-audit-report\" has been uploaded with full details.`;
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `Automated security: ${total} npm audit vulnerabilities detected`,
                body,
              });
            } else {
              core.info('No vulnerabilities found by npm audit.');
            }
